name: test
on: [ push, pull_request ]
jobs:
  test:
    strategy:
      matrix:
        # os: [ ubuntu-latest, windows-latest, macOS-latest ]
        os: [ ubuntu-latest ]
        dc: [ dmd-2.098.1 ]
        arch: [ x86_64 ]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - name: Install D compiler
        uses: dlang-community/setup-dlang@v1
        with:
          compiler: ${{ matrix.dc }}
      - name: Build IRRE toolchain
        run: . ./script/build_tools.sh
      - name: Build test programs
        run: pip3 install sh && python3 ./script/make_tests.py
      - name: Run tests
        working-directory: ./src/irretool
        run: dub test --arch=${{ matrix.arch }}